config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :posts
  resources :pets
  resources :users
  resource :sessions, only: %i[new create destroy]
  root 'posts#index'
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/pet.rb
# frozen_string_literal: true

class Pet < ApplicationRecord
  mount_uploader :avatar, AvatarUploader
  validates :age, numericality: { greater_than_or_equal_to: 0 }
  validates :animal, :avatar, presence: true
  end

app/models/post.rb
# frozen_string_literal: true

class Post < ApplicationRecord
  mount_uploader :photo, PhotoUploader
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i.freeze
  attr_accessor :remember_token
  before_save { self.email = email.downcase }

  validates :name,  presence: true, length: { maximum: 20 }
  validates :email, presence: true, length: { maximum: 250 },
                    format: { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }
  validates :password, presence: true, length: { minimum: 6 }, allow_nil: true

  has_secure_password

  def authenticated?(remember_token)
    return false unless remember_digest

    BCrypt::Password.new(remember_digest).is_password?(remember_token)
  end

  def self.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST : BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
  end

  def self.new_token
    SecureRandom.urlsafe_base64
  end

  def remember
    self.remember_token = User.new_token
    update(remember_digest: User.digest(remember_token))
  end

  def forget
    update(remember_digest: nil)
  end
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include SessionsHelper
end

app/controllers/pets_controller.rb
# frozen_string_literal: true

class PetsController < ApplicationController
  def create
    @pet = Pet.new(pet_params)
    if @pet.save
      redirect_to pets_path
    else
      # This line overrides the default rendering behavior, which
      # would have been to render the "create" view.
      @users = User.pluck(:name, :id)
      render 'new'
    end
  end

  def destroy
    @pet = Pet.find(params[:id])
    redirect_to pets_path if @pet.destroy
  end

  def new
    @pet = Pet.new
    @users = User.pluck(:name, :id)
  end

  def index
    @pets = Pet.order(updated_at: :desc)
  end

  def show; end

  def edit
    @pet = Pet.find(params[:id])
    @users = User.pluck(:name, :id)
  end

  def update
    @pet = Pet.find(params[:id])
    if @pet.update(pet_params)
      redirect_to pets_path
    else
      render 'edit'
    end
  end

  private

  def pet_params
    params.require(:pet).permit(:name, :animal, :avatar, :age)
  end
end

app/controllers/posts_controller.rb
# frozen_string_literal: true

class PostsController < ApplicationController
  def index
    @posts = Post.all.order(id: :desc)
  end

  def new
    @post = Post.new
    @pets = Pet.pluck(:name, :id)
    redirect_to posts_path if @post.save
  end

  def create
    # This action uses POST parameters. They are most likely coming
    # from an HTML form which the user has submitted. The URL for
    # this RESTful request will be "/clients", and the data will be
    # sent as part of the request body.
    @post = Post.new(post_params)
    if @post.save
      redirect_to @post
    else
      # This line overrides the default rendering behavior, which
      # would have been to render the "create" view.
      render 'new'
    end
  end

  def show
    @post = Post.find(params[:id])
  end

  def edit
    @post = Post.find(params[:id])
  end

  def update
    @post = Post.find(params[:id])
    if @post.update(post_params)
      redirect_to @post
    else
      render 'edit'
    end
  end

  def destroy
    @post = Post.find(params[:id])
    redirect_to posts_path if @post.destroy
  end

  private

  def post_params
    params.require(:post).permit(:weight, :description, :photo)
  end
end

app/controllers/sessions_controller.rb
# frozen_string_literal: true

class SessionsController < ApplicationController
  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user&.authenticate(params[:session][:password])
      log_in user
      params[:session][:remember_me] == '1' ? remember(user) : forget(user)
      redirect_back_or user
    else
      flash.now[:error] = 'Invalid email/password combination'
      render 'new'
    end
  end

  def destroy
    log_out if logged_in?
  end
end

app/controllers/users_controller.rb
# frozen_string_literal: true

class UsersController < ApplicationController
  before_action :logged_in_user, only: [:index, :edit, :update, :destroy]
  before_action :correct_user,   only: [:edit, :update]
  before_action :admin_user,     only: :destroy

  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      log_in @user
      redirect_to user_path(@user)
    else
      render 'new'
    end
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      flash[:success] = 'Profile updated'
      redirect_to @user
    else
      render 'edit'
    end
  end

  def destroy
    User.find(params[:id]).destroy
    flash[:success] = "User deleted"
    redirect_to users_path
  end

  def logged_in_user
    unless logged_in?
      store_location
      flash[:success] = 'Please log in'
      redirect_to new_sessions_path
    end
  end

  def correct_user
    @user = User.find(params[:id])
    redirect_to(root_path) unless current_user?(@user)
  end

  def admin_user
    redirect_to(root_path) unless current_user.admin?
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :password)
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
  def flash_class(level)
    case level
    when 'notice' then 'alert alert-info'
    when 'success' then 'alert alert-success'
    when 'error' then 'alert alert-danger'
    when 'alert' then 'alert alert-error'
    end
  end
end

app/helpers/pets_helper.rb
# frozen_string_literal: true

module PetsHelper
end

app/helpers/posts_helper.rb
# frozen_string_literal: true

module PostsHelper
end

app/helpers/sessions_helper.rb
# frozen_string_literal: true

module SessionsHelper
  def log_in(user)
    session[:user_id] = user.id
  end

  def remember(user)
    user.remember
    cookies.permanent.signed[:user_id] = user.id
    cookies.permanent[:remember_token] = user.remember_token
  end

  def current_user
    if (user_id = session[:user_id])
      @current_user ||= User.find_by(id: user_id)
    elsif (user_id = cookies.signed[:user_id])
      user = User.find_by(id: user_id)
      if user&.authenticated?(cookies[:remember_token])
        log_in user
        @current_user = user
      end
    end
  end

  def logged_in?
    current_user.present?
  end

  def forget(user)
    user.forget
    cookies.delete(:user_id)
    cookies.delete(:remember_token)
  end

  def log_out
    forget(current_user)
    session[:user_id] = nil
    redirect_to root_path
  end

  def current_user?(user)
    user == current_user
  end

  def redirect_back_or(default)
    redirect_to(session[:forwarding_url] || default)
    session.delete(:forwarding_url)
  end

  def store_location
    session[:forwarding_url] = request.original_url if request.get?
  end
end

app/helpers/users_helper.rb
# frozen_string_literal: true

module UsersHelper
  def gravatar_for(user, options = { size: 80 })
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    size = options[:size]
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
    image_tag(gravatar_url, alt: user.name, class: "gravatar")
  end
end

app/views/layouts/_flashes.html.slim
.flashes
  - flash.each do |key, msg|
    p class=flash_class(key) = msg

app/views/layouts/application.html.slim
doctype html
html
  head
    meta charset="utf-8"
    meta content="width=device-width, initial-scale=1, shrink-to-fit=no" name="viewport"
    meta content="" name="description"
    meta content="" name="author"
    title Fit Your Pet
    link rel="shortcut icon" href="/images/shiba-pixilart.ico"
    = csrf_meta_tags
    = csp_meta_tag

    = stylesheet_link_tag    'application', media: 'all'
    = javascript_include_tag 'application'

  body
    .container
      nav.navbar.navbar-expand-lg.navbar-light.bg-light
        img.logo src="/images/shiba-logo.png"
        a.navbar-brand.font-weight-bold href="/" Fit Your Pet
        button.navbar-toggler aria-controls="navbarSupportedContent" aria-expanded="false" aria-label=("Toggle navigation") data-target="#navbarSupportedContent" data-toggle="collapse" type="button"
          span.navbar-toggler-icon
        #navbarSupportedContent.collapse.navbar-collapse
          ul.navbar-nav.ml-auto
            li.nav-item.active
              a.nav-link href="/"
                | Stories
                span.sr-only (current)
            li.nav-item
              a.nav-link href=new_post_path Add New Story
            li.nav-item
              a.nav-link href=pets_path Pets
            li.nav-item
              a.nav-link href=new_pet_path Add New Pet
            li.nav-item
              a.nav-link href=users_path List of Users

            - if logged_in?
              li.nav-item= link_to 'Log Out', sessions_path, method: :delete, class: :'nav-link'
            - else
              li.nav-item
                a.nav-link href=new_sessions_path Log in
              li.nav-item
                a.nav-link href=new_user_path Sign up

    main.container
      = render 'layouts/flashes'
      = yield

app/views/pets/_form.html.slim
.container
  .row
    .col-6
      = form_for pet do |f|
        .form-group
          label Name:
          = f.text_field :name, class: 'form-control'

        .form-group
          label Animal:
          = f.text_area :animal, class: 'form-control'


        .form-group
          label Avatar:
          = f.file_field :avatar, class: 'form-control'


        .form-group
          label Age:
          = f.text_field :age, class: 'form-control'

        .form-group
          label User:
          = f.select :user_id, @users

        = f.submit class: 'btn btn-info'

app/views/pets/edit.html.slim
.row
  .col
    h1 Edit Pet Info

= render 'form', pet: @pet

app/views/pets/index.html.slim
.row
  .col
    h1 Pets
    - @pets.each_slice(3).each do |pet_row|
      .row
          - pet_row.each do |pet|
            .col-sm-4
              .card data-id=pet.id
                - if pet.avatar
                  img.card-img-top alt=("Card image cap") src=asset_path(pet.avatar)
                .card-body
                  h5.card-title= pet.name
                  h6.card-subtitle.mb-2.text-muted= pet.animal
                  span.badge.badge-pill.badge-info.float-right= pet.age.to_i
                  = link_to 'Destroy', pet_path(pet),
                    data: { confirm: 'Are you sure?' }, method: :delete, class: 'btn btn-danger'
                  = link_to 'Edit', edit_pet_path(pet), class: 'btn btn-info'

app/views/pets/new.html.slim
.row
  .col
    h1 Add New Pet

= render 'form', pet: @pet

app/views/pets/show.html.slim
h1 Pets#show
p Find me in app/views/pets/show.html.slim

app/views/posts/index.html.slim
.row
  .col
    h1 Weight Diary
    - @posts.each_slice(2) do |post_row|
      .row
        - post_row.each do |post|
          .col-sm-6
            .card data-id=post.id
              - if post.photo
                img.card-img-top alt=("Card image cap") src=asset_path(post.photo)
              .card-body
                h5.card-title
                  = post.created_at.strftime("%d %B")
                  span.badge.badge-pill.badge-info.float-right= post.created_at.strftime("%H:%M")
                  span.badge.badge-pill.badge-danger.float-right= post.weight
                p.card-text= post.description
                = link_to 'Destroy', post_path(post),
                  data: { confirm: 'Are you sure?' }, method: :delete, class: 'btn btn-danger'

app/views/posts/new.html.slim
.row
  .col
    h1 Add New Story

.container
  /form
  /.form-group
  /  label Weight
  /  input.form-control placeholder=("Enter weight")
  /  .form-group
  /    label Comment
  /    input.form-control placeholder=("Your comment")
  /  .form-group
  /    label Syrnik Photo
  /    input.form-control-file type="file"
  /  button.btn.btn-info type="submit"  Submit
  .row
    .col-6
      = form_for @post do |f|
        .form-group
          label Weight:
          = f.text_field :weight, class: 'form-control'

        .form-group
          label Description:
          = f.text_area :description, class: 'form-control'


        .form-group
          label Photo:
          = f.file_field :photo, class: 'form-control'

        .form-group
          label Pet:
          = f.select :pet_id, @pets



        = f.submit class: 'btn btn-info'

app/views/users/edit.html.slim
- provide(:title, "Edit user")
h1 Update your profile
.row
  .col
    = form_for(@user) do |f|

      = f.label :name
      = f.text_field :name, class: 'form-control'

      = f.label :email
      = f.email_field :email, class: 'form-control'

      = f.label :password
      = f.password_field :password, class: 'form-control'

      = f.label :password_confirmation, "Confirmation"
      = f.password_field :password_confirmation, class: 'form-control'
      = f.submit "Save changes", class: "btn btn-primary"
      end
    .gravatar_edit
      = gravatar_for @user
      a href="http://gravatar.com/emails" target="_self" Change

app/views/users/index.html.slim
.row
  .col
    h1 Users Information
    .card-deck
      - @users.each do |user|
        .card style=("width: 18rem;") data-id=user.id
          = gravatar_for user, size: 400
          .card-body
            h5.card-title
              = user.name
              span.badge.badge-pill.badge-info.float-right = user.created_at.strftime("%-d %B, %Y")
            p.card-text= user.email
            -  if current_user.admin? && !current_user?(user)
              = link_to 'Destroy', user_path(user),
                data: { confirm: 'Are you sure?' }, method: :delete, class: 'btn btn-danger'

app/views/users/new.html.slim
- provide(:title, 'Sign up')
h1 Sign up
.row
  .col-md-6.col-md-offset-3
    = form_for(@user) do |f|
      .form-group
        = f.label :name
        = f.text_field :name, class: "form-control", placeholder: "Name"

      .form-group
        = f.label :email
        = f.email_field :email, class: "form-control", placeholder: "E-mail"

      .form-group
        = f.label :password
        = f.password_field :password, class: "form-control", placeholder: "Password"

      .form-group
        = f.label :password_confirmation
        = f.password_field :password, class: "form-control", placeholder: "Password Confirmation"

      = f.submit "Create my account", class: "btn btn-primary"

app/views/users/show.html.slim
- provide(:title, @user.name)
.row
  aside.col-md-4
    section.user_info
      h1
        = gravatar_for @user
        = @user.name